
spring:
  profiles:
    active: ameet
---
spring:
  profiles: ameet
my:
    krb: "C:\\Users\\ameet\\Documents\\anthem\\source\\hbase_interact\\src\\main\\resources\\krb5.conf"
    keytab: "C:\\Users\\ameet\\Documents\\anthem\\source\\hbase_interact\\src\\main\\resources\\hbase_interact.keytab"
    table: "ameet_db:ameet_dq"
    type4File: "type4_sample.dat"
    small: "C:\\Users\\ameet\\Documents\\anthem\\source\\hbase_interact\\src\\main\\resources\\sample_hbase.csv"
    med: "C:\\Users\\ameet\\Documents\\anthem\\source\\hbase_interact\\src\\main\\resources\\sample_10k_hbase.csv"
    large: "C:\\Users\\ameet\\Documents\\anthem\\source\\hbase_interact\\src\\main\\resources\\sample_large_hbase.csv"
    data: "C:\\Users\\ameet\\Documents\\anthem\\source\\hbase_interact\\src\\main\\resources\\type4_in_dup.dat"
    outputDir: "C:\\Users\\ameet\\Documents\\anthem\\source\\hbase_interact\\src\\main\\resources\\output\\"
    bucketSize: 100
    threadPoolSize: 6
    thresholdSec: 5
    backpressure: 50
    threadPrefix: "hbaseRx-%d"
    user: "ameet@DEVAD.AMEET.COM"
    column: "sanity_col"
---
spring:
  profiles: dev
my:
    krb: /home/ameet/app/hbase_interact/src/main/resources/krb5.conf
    keytab: /home/ameet/app/hbase_interact/src/main/resources/hbase_interact.keytab
    table: "ameet_db:ameet_dq"
    small: /home/ameet/app/hbase_interact/src/main/resources/sample_hbase.csv
    data: /home/ameet/app/hbase_interact/data/Sample_220K_unique.txt
    outputDir: /home/ameet/app/hbase_interact/data/output
    bucketSize: 5000
    threadPoolSize: 75
    thresholdSec: 5
    backpressure: 75
    threadPrefix: "hbaseRx-%d"
    user: "ameet@DEVAD.AMEET.COM"
    column: "sanity_col"